var annotated_dup =
[
    [ "core", "namespacecore.html", "namespacecore" ],
    [ "l2d", "namespacel2d.html", "namespacel2d" ],
    [ "x", "namespacex.html", "namespacex" ],
    [ "_G", "class___g.html", "class___g" ],
    [ "any", "classany.html", null ],
    [ "async", "classasync.html", "classasync" ],
    [ "bit", "classbit.html", "classbit" ],
    [ "boolean", "classboolean.html", null ],
    [ "coroutine", "classcoroutine.html", "classcoroutine" ],
    [ "debug", "classdebug.html", "classdebug" ],
    [ "ffi", "classffi.html", "classffi" ],
    [ "file", "classfile.html", "classfile" ],
    [ "function", "classfunction.html", null ],
    [ "io", "classio.html", "classio" ],
    [ "jit", "classjit.html", "classjit" ],
    [ "local", "classlocal.html", null ],
    [ "lstg", "classlstg.html", "classlstg" ],
    [ "math", "classmath.html", "classmath" ],
    [ "nil", "classnil.html", null ],
    [ "number", "classnumber.html", null ],
    [ "object", "classobject.html", "classobject" ],
    [ "os", "classos.html", "classos" ],
    [ "package", "classpackage.html", "classpackage" ],
    [ "plus", "classplus.html", "classplus" ],
    [ "std", "classstd.html", "classstd" ],
    [ "string", "classstring.html", "classstring" ],
    [ "table", "classtable.html", "classtable" ],
    [ "thread", "classthread.html", null ],
    [ "userdata", "classuserdata.html", null ],
    [ "xobject", "classxobject.html", "classxobject" ],
    [ "xobject3d", "classxobject3d.html", "classxobject3d" ]
];